<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Train Line Assignment suite" duration-ms="74037" started-at="2018-12-31T02:22:55Z" finished-at="2018-12-31T02:24:09Z">
    <groups>
    </groups>
    <test name="Ticket Fare Test" duration-ms="74037" started-at="2018-12-31T02:22:55Z" finished-at="2018-12-31T02:24:09Z">
      <class name="com.trainline.qa.tests.DemoTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.trainline.qa.tests.DemoTest@32a068d1]" name="setup" is-config="true" duration-ms="9285" started-at="2018-12-31T07:52:55Z" finished-at="2018-12-31T07:53:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="demoTest()[pri:0, instance:com.trainline.qa.tests.DemoTest@32a068d1]" name="demoTest" duration-ms="23" started-at="2018-12-31T07:53:04Z" finished-at="2018-12-31T07:53:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at com.trainline.qa.tests.DemoTest.demoTest(DemoTest.java:35)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.trainline.qa.tests.DemoTest@32a068d1]" name="tearDown" is-config="true" duration-ms="723" started-at="2018-12-31T07:53:04Z" finished-at="2018-12-31T07:53:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.trainline.qa.tests.DemoTest@32a068d1]" name="setup" is-config="true" duration-ms="7721" started-at="2018-12-31T07:53:05Z" finished-at="2018-12-31T07:53:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="demoTest()[pri:0, instance:com.trainline.qa.tests.DemoTest@32a068d1]" name="demoTest" duration-ms="2" started-at="2018-12-31T07:53:13Z" finished-at="2018-12-31T07:53:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at com.trainline.qa.tests.DemoTest.demoTest(DemoTest.java:35)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.trainline.qa.tests.DemoTest@32a068d1]" name="tearDown" is-config="true" duration-ms="663" started-at="2018-12-31T07:53:14Z" finished-at="2018-12-31T07:53:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.trainline.qa.tests.DemoTest -->
      <class name="com.trainline.qa.tests.TicketFareTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.trainline.qa.tests.TicketFareTest@33cb5951]" name="setUp" is-config="true" duration-ms="12888" started-at="2018-12-31T07:53:15Z" finished-at="2018-12-31T07:53:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyTicketFare(java.lang.String, java.lang.String)[pri:0, instance:com.trainline.qa.tests.TicketFareTest@33cb5951]" name="verifyTicketFare" duration-ms="39831" started-at="2018-12-31T07:53:28Z" data-provider="getData" finished-at="2018-12-31T07:54:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Row House No 5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Gajanana Society]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTicketFare -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.trainline.qa.tests.TicketFareTest@33cb5951]" name="tearDown" is-config="true" duration-ms="752" started-at="2018-12-31T07:54:08Z" finished-at="2018-12-31T07:54:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.trainline.qa.tests.TicketFareTest -->
    </test> <!-- Ticket Fare Test -->
  </suite> <!-- Train Line Assignment suite -->
</testng-results>
